version: 2
jobs:
    build:
        working_directory: ./.circleci
        docker:
            - image: circleci/node
        steps:
            - checkout
            - run:
                name: update-npm
                command: 'sudo npm install -g npm@latest'
            - restore_cache:
                key: dependency-cache-{{ checksum "package.json" }}
            - run:
                name: install packages
                command: npm install
            - save_cache:
                key: dependency-cache-{{ checksum "package.json" }}
                paths:
                    - ./node_modules
            - run:
                name: test
                command: npm test
            - run:
                name: code-coverage
                command: './node_modules/.bin/nyc report --reporter=text-lcov'


